spring:
  profiles:
    active: prod
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  batch:
    job:
      enabled: false

springdoc:
  default-produces-media-type: application/json

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.coffee.domain.order.service.OrderBatchService: DEBUG

    com.rest1: DEBUG


# 탈퇴고객 일괄수거 스케줄링 파라미터 설정
custom:
  customer:
    scheduler:
      cron: "0 * * * * ?"             # 매 1분마다 실행 (테스트용)
      # cron: "0 0 3 * * ?"             # 새벽 3시 (운영용)
      purge-threshold: 1         # 삭제 기준일: 1분 전 (테스트용)
      # purge-threshold: 7         # 삭제 기준일: 7일 전 (운영용)
